#Lunch combos for AoCP
add_lunch_combo aocp_ace-userdebug
add_lunch_combo aocp_crespo-userdebug
add_lunch_combo aocp_captivatemtd-userdebug
add_lunch_combo aocp_d710-userdebug
add_lunch_combo aocp_d2att-userdebug
add_lunch_combo aocp_i777-userdebug
add_lunch_combo aocp_maguro-userdebug
add_lunch_combo aocp_quincyatt-userdebug
add_lunch_combo aocp_skyrocket-userdebug
add_lunch_combo aocp_toro-userdebug
add_lunch_combo aocp_holiday-userdebug
add_lunch_combo aocp_mako-userdebug
add_lunch_combo aocp_t0lteatt-userdebug
add_lunch_combo aocp_d2spr-userdebug
add_lunch_combo aocp_p5110-userdebug
#



